function PRP_Constants() {}

PRP_Constants.TOGAF_PREDECESSOR_CONNECTION_TYPE = Constants.CT_CRT_1;
PRP_Constants.TOGAF_SUCCESSOR_CONNECTION_TYPE = Constants.CT_ACTIV_1;

PRP_Constants.PREDECESSOR = 0;
PRP_Constants.SUCCESSOR = 1;
PRP_Constants.ADS_ITEM_TYPE_GROUP = 0;
PRP_Constants.ADS_ITEM_TYPE_FILE = 1;


PRP_Constants.TOGAF_EVENT_TYPE = Constants.OT_EVT;
PRP_Constants.TOGAF_EVENT_SYMBOL = Constants.ST_EV;
PRP_Constants.TOGAF_PREDECESSOR_TYPE = Constants.OT_FUNC;
PRP_Constants.TOGAF_PREDECESSOR_SYMBOL = Constants.ST_FUNC;
PRP_Constants.TOGAF_PREDECESSOR_CONNECTION_TYPE = Constants.CT_CRT_1;
PRP_Constants.TOGAF_SUCCESSOR_TYPE = Constants.OT_FUNC;
PRP_Constants.TOGAF_SUCCESSOR_SYMBOL = Constants.ST_FUNC;
PRP_Constants.TOGAF_SUCCESSOR_CONNECTION_TYPE = Constants.CT_ACTIV_1;

PRP_Constants.TOGAF_BRAND_TYPE = Constants.OT_ORG_UNIT;
PRP_Constants.TOGAF_BRAND_SYMBOL = Constants.ST_ORG_UNIT_2;

PRP_Constants.TOGAF_PLANT_TYPE = Constants.OT_LOC;
PRP_Constants.TOGAF_PLANT_SYMBOL = Constants.ST_LOC_1;

PRP_Constants.TOGAF_INTERFACE_SYMBOL = Constants.ST_IF;
PRP_Constants.TOGAF_INTERFACE_TYPE = Constants.OT_CLS;
PRP_Constants.TOGAF_INTERFACE_CONNECTION_TYPE = Constants.CT_HAS_STATE;
PRP_Constants.TOGAF_INTERFACE_IT_SYSTEM_CONNECTION_TYPE = Constants.CT_USE_1;
PRP_Constants.TOGAF_INTERFACE_TO_INTERFACE_CONNECTION_TYPE = Constants.CT_ASSOCIA;


PRP_Constants.TOGAF_PLANT_OR_BRAND_CONNECTION_TYPE = Constants.CT_ACS_2;

PRP_Constants.TOGAF_DATA_OBJECT_TYPE = Constants.OT_CLST;
PRP_Constants.TOGAF_DATA_OBJECT_SYMBOL = Constants.ST_CLST;
PRP_Constants.TOGAF_DATA_OBJECT_CONNECTION_TYPE = Constants.CT_HAS_STATE;

PRP_Constants.TOGAF_IT_SYSTEM_SYMBOL = Constants.ST_APPL_SYS_TYPE;
PRP_Constants.TOGAF_IT_SYSTEM_CONNECTION_TYPE = Constants.CT_SENDS_3;
PRP_Constants.TOGAF_IT_SYSTEM_DATA_OBJECT_CONNECTION_TYPE = Constants.CT_HAS_OUT;
PRP_Constants.TOGAF_DATA_OBJECT_IT_SYSTEM_CONNECTION_TYPE = Constants.CT_IS_INP_FOR;

PRP_Constants.TOGAF_COMMITTEE_OBJECT_TYPE = Constants.OT_GRP;
PRP_Constants.TOGAF_COMMITTEE_SYMBOL = Constants.ST_GRP;

PRP_Constants.TOGAF_BRAND_TO_PLANT_CONNECTION_TYPE = Constants.CT_IS_LOC_AT_1;
PRP_Constants.TOGAF_COMMITTE_TO_BRAND_CONNECTION_TYPE = Constants.CT_IS_ASSIG_1;
PRP_Constants.TOGAF_COMMITTEE_TO_INTERFACE_CONNNECTION_TYPE = Constants.CT_ACS_2
PRP_Constants.TOGAF_DOCUMENT_INTERFACE_CONNECTION_TYPE = Constants.CT_DEPICTS_2;



PRP_Constants.IE_DATA_MODEL_TYPE = Constants.MT_IEF_DATA_MDL;
PRP_Constants.RELEVANT_OBJECT_TYPE = Constants.OT_ERM_ATTR;
PRP_Constants.RELEVANT_OBJECT_SYMBOL = Constants.ST_DESC_ATTR;
PRP_Constants.RELEVANT_OBJECT_CONNECTION_TYPE = Constants.CT_CONS_OF_2;
PRP_Constants.IT_SYSTEM = Constants.OT_APPL_SYS_TYPE;
PRP_Constants.DOCUMENT_TYPE = Constants.OT_INFO_CARR;
PRP_Constants.DOCUMENT_SYMBOL = Constants.ST_INFO_CARR;


PRP_Constants.dataObjectFolder = "2760f7a1-8faa-11ea-0517-005056af26e2";
PRP_Constants.ERM_ATTRIBUTE_GROUP_GUID = "b7797481-04d8-11ec-41e3-005056af26e2";
PRP_Constants.IT_SYSTEM_ROOT_GROUP_GUID = "29e13850-3f0e-11eb-7590-005056af26e2";
PRP_Constants.DOCUMENTS_ROOT_GROUP_GUID = "302b3101-178c-11ec-41e3-005056af26e2";

//Custom VWG Conventions
//PRP_Constants.BRAND_SYMBOL_STD = ArisData.ActiveFilter().UserDefinedSymbolTypeNum("8f618f50-57b9-11e5-255f-0017a4773c28");
//PRP_Constants.COMPANY_SYMBOL_STD = ArisData.ActiveFilter().UserDefinedSymbolTypeNum("0ab65310-57bb-11e5-255f-0017a4773c28");

//new (std) modeling Conventions
PRP_Constants.BRAND_SYMBOL_STD = Constants.ST_GRP;
PRP_Constants.COMPANY_SYMBOL_STD = Constants.ST_ORG_UNIT_1;
PRP_Constants.COMPANIES_OVERVIEW_MODEL = "4dd85bb7-005e-414f-bab3-a70eb76b79ab";
PRP_Constants.ADS_FOLDER_NAME = "PRP Pilot";

PRP_Constants.PRECEDING_COMPLETION_ATTRIBUTE = ArisData.ActiveFilter().UserDefinedAttributeTypeNum("9528d7d1-9040-11ea-3cf0-005056af6d0b");
PRP_Constants.SUCCEEDING_COMPLETION_ATTRIBUTE = ArisData.ActiveFilter().UserDefinedAttributeTypeNum("b61e8f71-3b3e-11ec-2e39-005056af6d0b");
PRP_Constants.OVERALL_COMPLETION_ATTRIBUTE = ArisData.ActiveFilter().UserDefinedAttributeTypeNum("8227d631-3b3f-11ec-2e39-005056af6d0b");
PRP_Constants.PRP_STORY_ATTRIBUTE = ArisData.ActiveFilter().UserDefinedAttributeTypeNum("00ac6891-cede-11e7-45d9-0050568107bf");

PRP_Constants.IS_PRP_ATTRIBUTE =  ArisData.ActiveFilter().UserDefinedAttributeTypeNum("090addd1-8fae-11ea-3cf0-005056af6d0b");
PRP_Constants.PROCESS_OWNER_ATTRIBUTE = ArisData.ActiveFilter().UserDefinedAttributeTypeNum("4584c780-825e-11de-7e09-001a6b3c78e6");

PRP_Constants.FAD_MODEL_TYPE = Constants.MT_FUNC_ALLOC_DGM;
PRP_Constants.PROCESS_OWNER_CONNECTION_TYPE = Constants.CT_DECD_ON;
PRP_Constants.EPC_MODEL_TYPE = Constants.MT_EEPC;
PRP_Constants.BPMN_COLLABORATION_DIAGRAM_MODEL_TYPE = Constants.MT_ENTERPRISE_BPMN_COLLABORATION;
PRP_Constants.BPMN_PROCESS_DIAGRAM_MODEL_TYPE = Constants.MT_ENTERPRISE_BPMN_PROCESS;

PRP_Constants.MULTIPLE_PROCESS_OWNERS_ERROR_MESSAGE = "Error: Multiple owners found";


//TEMPLATE_GUID = "90035e81-4129-11d4-857d-00005a4053ff"; //Reset
//TEMPLATE_GUID = "86a03d80-c530-11e7-386a-0050568107bf"; //VW Aftersales_Industry.PerformanceREADY
TEMPLATE_GUID = "1ddcf050-2831-11ec-2e38-005056af6d0b"; //VWG - New conventions


